PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO courses(id,title,description,language,level,tags,thumbnail_url,total_lessons,total_xp,estimated_duration,is_published,created_at,updated_at)
VALUES('course-en-zero-69','Tiếng Anh từ con số 0 – 69 bài','Lộ trình học tuần tự dựa trên 4 tài liệu của người học: Ngữ pháp Tiếng Anh (23 chủ điểm nền tảng/mở rộng), Bài tập Tiếng Anh 6 Tập 1–2 để luyện phát âm, từ vựng, ngữ pháp, nói, đọc, viết; Giải thích ngữ pháp Tiếng Anh dùng làm tài liệu giải thích bổ sung.','en','A1','["beginner","zero-to-basic","grammar","vocabulary","pronunciation","pdf-course"]',NULL,69,805,1495,1,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

INSERT OR IGNORE INTO units(id,course_id,title,description,order_index,background_color,icon_url,total_lessons,created_at,updated_at)
VALUES('unit-zero-u01','course-en-zero-69','Chủ điểm 1: The Alphabet and Noun','Bảng chữ cái, nguyên âm/phụ âm, danh từ và a/an. Nguồn: Ngữ pháp Tiếng Anh – Unit 1.',0,NULL,NULL,3,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u01-01','unit-zero-u01','Hiểu bài: The Alphabet and Noun','Giải thích từ nền tảng, dùng ví dụ ngắn và dễ hiểu. Nguồn: Ngữ pháp Tiếng Anh – Unit 1.','Nắm được quy tắc chính của The Alphabet and Noun.',0,'lesson',10,75,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 1","lesson_stage":"learn","sections":["Giải thích","Ví dụ","Từ/cụm cần nhớ"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u01-02','unit-zero-u01','Luyện tập: The Alphabet and Noun','Luyện nhận biết, điền từ, chọn đáp án và sửa lỗi theo tài liệu nguồn. Nguồn: Ngữ pháp Tiếng Anh – Unit 1.','Làm đúng các dạng bài cơ bản của The Alphabet and Noun.',1,'practice',10,80,0,25,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 1","lesson_stage":"practice","sections":["Nhận biết","Điền/chọn đáp án","Sửa lỗi"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u01-03','unit-zero-u01','Ứng dụng & kiểm tra: The Alphabet and Noun','Đặt câu, dịch Việt–Anh, nói/viết ngắn và kiểm tra cuối chủ điểm. Nguồn: Ngữ pháp Tiếng Anh – Unit 1.','Tự dùng The Alphabet and Noun trong câu đơn giản và đạt tối thiểu 80%.',2,'quiz',15,80,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 1","lesson_stage":"apply-test","sections":["Đặt câu","Dịch Việt–Anh","Nói/viết ngắn","Kiểm tra"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

INSERT OR IGNORE INTO units(id,course_id,title,description,order_index,background_color,icon_url,total_lessons,created_at,updated_at)
VALUES('unit-zero-u02','course-en-zero-69','Chủ điểm 2: Plural Nouns','Danh từ số nhiều: -s, -es và các dạng bất quy tắc cơ bản. Nguồn: Ngữ pháp Tiếng Anh – Unit 2.',1,NULL,NULL,3,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u02-01','unit-zero-u02','Hiểu bài: Plural Nouns','Giải thích từ nền tảng, dùng ví dụ ngắn và dễ hiểu. Nguồn: Ngữ pháp Tiếng Anh – Unit 2.','Nắm được quy tắc chính của Plural Nouns.',0,'lesson',10,75,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 2","lesson_stage":"learn","sections":["Giải thích","Ví dụ","Từ/cụm cần nhớ"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u02-02','unit-zero-u02','Luyện tập: Plural Nouns','Luyện nhận biết, điền từ, chọn đáp án và sửa lỗi theo tài liệu nguồn. Nguồn: Ngữ pháp Tiếng Anh – Unit 2.','Làm đúng các dạng bài cơ bản của Plural Nouns.',1,'practice',10,80,0,25,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 2","lesson_stage":"practice","sections":["Nhận biết","Điền/chọn đáp án","Sửa lỗi"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u02-03','unit-zero-u02','Ứng dụng & kiểm tra: Plural Nouns','Đặt câu, dịch Việt–Anh, nói/viết ngắn và kiểm tra cuối chủ điểm. Nguồn: Ngữ pháp Tiếng Anh – Unit 2.','Tự dùng Plural Nouns trong câu đơn giản và đạt tối thiểu 80%.',2,'quiz',15,80,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 2","lesson_stage":"apply-test","sections":["Đặt câu","Dịch Việt–Anh","Nói/viết ngắn","Kiểm tra"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

INSERT OR IGNORE INTO units(id,course_id,title,description,order_index,background_color,icon_url,total_lessons,created_at,updated_at)
VALUES('unit-zero-u03','course-en-zero-69','Chủ điểm 3: Personal Pronouns','Đại từ nhân xưng: I, you, we, they, he, she, it. Nguồn: Ngữ pháp Tiếng Anh – Unit 3.',2,NULL,NULL,3,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u03-01','unit-zero-u03','Hiểu bài: Personal Pronouns','Giải thích từ nền tảng, dùng ví dụ ngắn và dễ hiểu. Nguồn: Ngữ pháp Tiếng Anh – Unit 3.','Nắm được quy tắc chính của Personal Pronouns.',0,'lesson',10,75,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 3","lesson_stage":"learn","sections":["Giải thích","Ví dụ","Từ/cụm cần nhớ"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u03-02','unit-zero-u03','Luyện tập: Personal Pronouns','Luyện nhận biết, điền từ, chọn đáp án và sửa lỗi theo tài liệu nguồn. Nguồn: Ngữ pháp Tiếng Anh – Unit 3.','Làm đúng các dạng bài cơ bản của Personal Pronouns.',1,'practice',10,80,0,25,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 3","lesson_stage":"practice","sections":["Nhận biết","Điền/chọn đáp án","Sửa lỗi"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u03-03','unit-zero-u03','Ứng dụng & kiểm tra: Personal Pronouns','Đặt câu, dịch Việt–Anh, nói/viết ngắn và kiểm tra cuối chủ điểm. Nguồn: Ngữ pháp Tiếng Anh – Unit 3.','Tự dùng Personal Pronouns trong câu đơn giản và đạt tối thiểu 80%.',2,'quiz',15,80,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 3","lesson_stage":"apply-test","sections":["Đặt câu","Dịch Việt–Anh","Nói/viết ngắn","Kiểm tra"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

INSERT OR IGNORE INTO units(id,course_id,title,description,order_index,background_color,icon_url,total_lessons,created_at,updated_at)
VALUES('unit-zero-u04','course-en-zero-69','Chủ điểm 4: Verb “To Be”','am/is/are trong câu khẳng định, phủ định và câu hỏi. Nguồn: Ngữ pháp Tiếng Anh – Unit 4.',3,NULL,NULL,3,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u04-01','unit-zero-u04','Hiểu bài: Verb “To Be”','Giải thích từ nền tảng, dùng ví dụ ngắn và dễ hiểu. Nguồn: Ngữ pháp Tiếng Anh – Unit 4.','Nắm được quy tắc chính của Verb “To Be”.',0,'lesson',10,75,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 4","lesson_stage":"learn","sections":["Giải thích","Ví dụ","Từ/cụm cần nhớ"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u04-02','unit-zero-u04','Luyện tập: Verb “To Be”','Luyện nhận biết, điền từ, chọn đáp án và sửa lỗi theo tài liệu nguồn. Nguồn: Ngữ pháp Tiếng Anh – Unit 4.','Làm đúng các dạng bài cơ bản của Verb “To Be”.',1,'practice',10,80,0,25,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 4","lesson_stage":"practice","sections":["Nhận biết","Điền/chọn đáp án","Sửa lỗi"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u04-03','unit-zero-u04','Ứng dụng & kiểm tra: Verb “To Be”','Đặt câu, dịch Việt–Anh, nói/viết ngắn và kiểm tra cuối chủ điểm. Nguồn: Ngữ pháp Tiếng Anh – Unit 4.','Tự dùng Verb “To Be” trong câu đơn giản và đạt tối thiểu 80%.',2,'quiz',15,80,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 4","lesson_stage":"apply-test","sections":["Đặt câu","Dịch Việt–Anh","Nói/viết ngắn","Kiểm tra"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

INSERT OR IGNORE INTO units(id,course_id,title,description,order_index,background_color,icon_url,total_lessons,created_at,updated_at)
VALUES('unit-zero-u05','course-en-zero-69','Chủ điểm 5: This / That / These / Those','Đại từ chỉ định cho vật/người gần và xa, số ít và số nhiều. Nguồn: Ngữ pháp Tiếng Anh – Unit 5.',4,NULL,NULL,3,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u05-01','unit-zero-u05','Hiểu bài: This / That / These / Those','Giải thích từ nền tảng, dùng ví dụ ngắn và dễ hiểu. Nguồn: Ngữ pháp Tiếng Anh – Unit 5.','Nắm được quy tắc chính của This / That / These / Those.',0,'lesson',10,75,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 5","lesson_stage":"learn","sections":["Giải thích","Ví dụ","Từ/cụm cần nhớ"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u05-02','unit-zero-u05','Luyện tập: This / That / These / Those','Luyện nhận biết, điền từ, chọn đáp án và sửa lỗi theo tài liệu nguồn. Nguồn: Ngữ pháp Tiếng Anh – Unit 5.','Làm đúng các dạng bài cơ bản của This / That / These / Those.',1,'practice',10,80,0,25,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 5","lesson_stage":"practice","sections":["Nhận biết","Điền/chọn đáp án","Sửa lỗi"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u05-03','unit-zero-u05','Ứng dụng & kiểm tra: This / That / These / Those','Đặt câu, dịch Việt–Anh, nói/viết ngắn và kiểm tra cuối chủ điểm. Nguồn: Ngữ pháp Tiếng Anh – Unit 5.','Tự dùng This / That / These / Those trong câu đơn giản và đạt tối thiểu 80%.',2,'quiz',15,80,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 5","lesson_stage":"apply-test","sections":["Đặt câu","Dịch Việt–Anh","Nói/viết ngắn","Kiểm tra"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

INSERT OR IGNORE INTO units(id,course_id,title,description,order_index,background_color,icon_url,total_lessons,created_at,updated_at)
VALUES('unit-zero-u06','course-en-zero-69','Chủ điểm 6: There Is / There Are','Mô tả sự tồn tại và đồ vật trong nhà; liên hệ My Home. Nguồn: Ngữ pháp Tiếng Anh – Unit 6; Bài tập Tiếng Anh 6 – Unit 2.',5,NULL,NULL,3,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u06-01','unit-zero-u06','Hiểu bài: There Is / There Are','Giải thích từ nền tảng, dùng ví dụ ngắn và dễ hiểu. Nguồn: Ngữ pháp Tiếng Anh – Unit 6; Bài tập Tiếng Anh 6 – Unit 2.','Nắm được quy tắc chính của There Is / There Are.',0,'lesson',10,75,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 6; Bài tập Tiếng Anh 6 – Unit 2","lesson_stage":"learn","sections":["Giải thích","Ví dụ","Từ/cụm cần nhớ"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u06-02','unit-zero-u06','Luyện tập: There Is / There Are','Luyện nhận biết, điền từ, chọn đáp án và sửa lỗi theo tài liệu nguồn. Nguồn: Ngữ pháp Tiếng Anh – Unit 6; Bài tập Tiếng Anh 6 – Unit 2.','Làm đúng các dạng bài cơ bản của There Is / There Are.',1,'practice',10,80,0,25,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 6; Bài tập Tiếng Anh 6 – Unit 2","lesson_stage":"practice","sections":["Nhận biết","Điền/chọn đáp án","Sửa lỗi"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u06-03','unit-zero-u06','Ứng dụng & kiểm tra: There Is / There Are','Đặt câu, dịch Việt–Anh, nói/viết ngắn và kiểm tra cuối chủ điểm. Nguồn: Ngữ pháp Tiếng Anh – Unit 6; Bài tập Tiếng Anh 6 – Unit 2.','Tự dùng There Is / There Are trong câu đơn giản và đạt tối thiểu 80%.',2,'quiz',15,80,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 6; Bài tập Tiếng Anh 6 – Unit 2","lesson_stage":"apply-test","sections":["Đặt câu","Dịch Việt–Anh","Nói/viết ngắn","Kiểm tra"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

INSERT OR IGNORE INTO units(id,course_id,title,description,order_index,background_color,icon_url,total_lessons,created_at,updated_at)
VALUES('unit-zero-u07','course-en-zero-69','Chủ điểm 7: Possessive','Tính từ sở hữu, đại từ sở hữu và cách nói “của ai”. Nguồn: Ngữ pháp Tiếng Anh – Unit 7.',6,NULL,NULL,3,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u07-01','unit-zero-u07','Hiểu bài: Possessive','Giải thích từ nền tảng, dùng ví dụ ngắn và dễ hiểu. Nguồn: Ngữ pháp Tiếng Anh – Unit 7.','Nắm được quy tắc chính của Possessive.',0,'lesson',10,75,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 7","lesson_stage":"learn","sections":["Giải thích","Ví dụ","Từ/cụm cần nhớ"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u07-02','unit-zero-u07','Luyện tập: Possessive','Luyện nhận biết, điền từ, chọn đáp án và sửa lỗi theo tài liệu nguồn. Nguồn: Ngữ pháp Tiếng Anh – Unit 7.','Làm đúng các dạng bài cơ bản của Possessive.',1,'practice',10,80,0,25,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 7","lesson_stage":"practice","sections":["Nhận biết","Điền/chọn đáp án","Sửa lỗi"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u07-03','unit-zero-u07','Ứng dụng & kiểm tra: Possessive','Đặt câu, dịch Việt–Anh, nói/viết ngắn và kiểm tra cuối chủ điểm. Nguồn: Ngữ pháp Tiếng Anh – Unit 7.','Tự dùng Possessive trong câu đơn giản và đạt tối thiểu 80%.',2,'quiz',15,80,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 7","lesson_stage":"apply-test","sections":["Đặt câu","Dịch Việt–Anh","Nói/viết ngắn","Kiểm tra"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

INSERT OR IGNORE INTO units(id,course_id,title,description,order_index,background_color,icon_url,total_lessons,created_at,updated_at)
VALUES('unit-zero-u08','course-en-zero-69','Chủ điểm 8: Prepositions of Time','in / on / at với giờ, ngày, tháng, năm và thời điểm. Nguồn: Ngữ pháp Tiếng Anh – Unit 8; Bài tập Tiếng Anh 6 – Unit 6.',7,NULL,NULL,3,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u08-01','unit-zero-u08','Hiểu bài: Prepositions of Time','Giải thích từ nền tảng, dùng ví dụ ngắn và dễ hiểu. Nguồn: Ngữ pháp Tiếng Anh – Unit 8; Bài tập Tiếng Anh 6 – Unit 6.','Nắm được quy tắc chính của Prepositions of Time.',0,'lesson',10,75,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 8; Bài tập Tiếng Anh 6 – Unit 6","lesson_stage":"learn","sections":["Giải thích","Ví dụ","Từ/cụm cần nhớ"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u08-02','unit-zero-u08','Luyện tập: Prepositions of Time','Luyện nhận biết, điền từ, chọn đáp án và sửa lỗi theo tài liệu nguồn. Nguồn: Ngữ pháp Tiếng Anh – Unit 8; Bài tập Tiếng Anh 6 – Unit 6.','Làm đúng các dạng bài cơ bản của Prepositions of Time.',1,'practice',10,80,0,25,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 8; Bài tập Tiếng Anh 6 – Unit 6","lesson_stage":"practice","sections":["Nhận biết","Điền/chọn đáp án","Sửa lỗi"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u08-03','unit-zero-u08','Ứng dụng & kiểm tra: Prepositions of Time','Đặt câu, dịch Việt–Anh, nói/viết ngắn và kiểm tra cuối chủ điểm. Nguồn: Ngữ pháp Tiếng Anh – Unit 8; Bài tập Tiếng Anh 6 – Unit 6.','Tự dùng Prepositions of Time trong câu đơn giản và đạt tối thiểu 80%.',2,'quiz',15,80,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 8; Bài tập Tiếng Anh 6 – Unit 6","lesson_stage":"apply-test","sections":["Đặt câu","Dịch Việt–Anh","Nói/viết ngắn","Kiểm tra"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

INSERT OR IGNORE INTO units(id,course_id,title,description,order_index,background_color,icon_url,total_lessons,created_at,updated_at)
VALUES('unit-zero-u09','course-en-zero-69','Chủ điểm 9: Prepositions of Place','in / on / at, under, behind, between, next to…; mô tả vị trí. Nguồn: Ngữ pháp Tiếng Anh – Unit 9; Bài tập Tiếng Anh 6 – Unit 2 & 4.',8,NULL,NULL,3,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u09-01','unit-zero-u09','Hiểu bài: Prepositions of Place','Giải thích từ nền tảng, dùng ví dụ ngắn và dễ hiểu. Nguồn: Ngữ pháp Tiếng Anh – Unit 9; Bài tập Tiếng Anh 6 – Unit 2 & 4.','Nắm được quy tắc chính của Prepositions of Place.',0,'lesson',10,75,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 9; Bài tập Tiếng Anh 6 – Unit 2 & 4","lesson_stage":"learn","sections":["Giải thích","Ví dụ","Từ/cụm cần nhớ"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u09-02','unit-zero-u09','Luyện tập: Prepositions of Place','Luyện nhận biết, điền từ, chọn đáp án và sửa lỗi theo tài liệu nguồn. Nguồn: Ngữ pháp Tiếng Anh – Unit 9; Bài tập Tiếng Anh 6 – Unit 2 & 4.','Làm đúng các dạng bài cơ bản của Prepositions of Place.',1,'practice',10,80,0,25,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 9; Bài tập Tiếng Anh 6 – Unit 2 & 4","lesson_stage":"practice","sections":["Nhận biết","Điền/chọn đáp án","Sửa lỗi"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u09-03','unit-zero-u09','Ứng dụng & kiểm tra: Prepositions of Place','Đặt câu, dịch Việt–Anh, nói/viết ngắn và kiểm tra cuối chủ điểm. Nguồn: Ngữ pháp Tiếng Anh – Unit 9; Bài tập Tiếng Anh 6 – Unit 2 & 4.','Tự dùng Prepositions of Place trong câu đơn giản và đạt tối thiểu 80%.',2,'quiz',15,80,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 9; Bài tập Tiếng Anh 6 – Unit 2 & 4","lesson_stage":"apply-test","sections":["Đặt câu","Dịch Việt–Anh","Nói/viết ngắn","Kiểm tra"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

INSERT OR IGNORE INTO units(id,course_id,title,description,order_index,background_color,icon_url,total_lessons,created_at,updated_at)
VALUES('unit-zero-u10','course-en-zero-69','Chủ điểm 10: Can and Basic Modals','can/can’t và thực hành must/mustn’t, should/shouldn’t trong các bài nguồn. Nguồn: Ngữ pháp Tiếng Anh – Unit 10; Bài tập Tiếng Anh 6 – Unit 5 & 6.',9,NULL,NULL,3,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u10-01','unit-zero-u10','Hiểu bài: Can and Basic Modals','Giải thích từ nền tảng, dùng ví dụ ngắn và dễ hiểu. Nguồn: Ngữ pháp Tiếng Anh – Unit 10; Bài tập Tiếng Anh 6 – Unit 5 & 6.','Nắm được quy tắc chính của Can and Basic Modals.',0,'lesson',10,75,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 10; Bài tập Tiếng Anh 6 – Unit 5 & 6","lesson_stage":"learn","sections":["Giải thích","Ví dụ","Từ/cụm cần nhớ"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u10-02','unit-zero-u10','Luyện tập: Can and Basic Modals','Luyện nhận biết, điền từ, chọn đáp án và sửa lỗi theo tài liệu nguồn. Nguồn: Ngữ pháp Tiếng Anh – Unit 10; Bài tập Tiếng Anh 6 – Unit 5 & 6.','Làm đúng các dạng bài cơ bản của Can and Basic Modals.',1,'practice',10,80,0,25,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 10; Bài tập Tiếng Anh 6 – Unit 5 & 6","lesson_stage":"practice","sections":["Nhận biết","Điền/chọn đáp án","Sửa lỗi"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u10-03','unit-zero-u10','Ứng dụng & kiểm tra: Can and Basic Modals','Đặt câu, dịch Việt–Anh, nói/viết ngắn và kiểm tra cuối chủ điểm. Nguồn: Ngữ pháp Tiếng Anh – Unit 10; Bài tập Tiếng Anh 6 – Unit 5 & 6.','Tự dùng Can and Basic Modals trong câu đơn giản và đạt tối thiểu 80%.',2,'quiz',15,80,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 10; Bài tập Tiếng Anh 6 – Unit 5 & 6","lesson_stage":"apply-test","sections":["Đặt câu","Dịch Việt–Anh","Nói/viết ngắn","Kiểm tra"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

INSERT OR IGNORE INTO units(id,course_id,title,description,order_index,background_color,icon_url,total_lessons,created_at,updated_at)
VALUES('unit-zero-u11','course-en-zero-69','Chủ điểm 11: Present Simple','Hiện tại đơn, thói quen, lịch học và trạng từ tần suất. Nguồn: Ngữ pháp Tiếng Anh – Unit 11; Bài tập Tiếng Anh 6 – Unit 1 & 7.',10,NULL,NULL,3,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u11-01','unit-zero-u11','Hiểu bài: Present Simple','Giải thích từ nền tảng, dùng ví dụ ngắn và dễ hiểu. Nguồn: Ngữ pháp Tiếng Anh – Unit 11; Bài tập Tiếng Anh 6 – Unit 1 & 7.','Nắm được quy tắc chính của Present Simple.',0,'lesson',10,75,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 11; Bài tập Tiếng Anh 6 – Unit 1 & 7","lesson_stage":"learn","sections":["Giải thích","Ví dụ","Từ/cụm cần nhớ"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u11-02','unit-zero-u11','Luyện tập: Present Simple','Luyện nhận biết, điền từ, chọn đáp án và sửa lỗi theo tài liệu nguồn. Nguồn: Ngữ pháp Tiếng Anh – Unit 11; Bài tập Tiếng Anh 6 – Unit 1 & 7.','Làm đúng các dạng bài cơ bản của Present Simple.',1,'practice',10,80,0,25,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 11; Bài tập Tiếng Anh 6 – Unit 1 & 7","lesson_stage":"practice","sections":["Nhận biết","Điền/chọn đáp án","Sửa lỗi"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u11-03','unit-zero-u11','Ứng dụng & kiểm tra: Present Simple','Đặt câu, dịch Việt–Anh, nói/viết ngắn và kiểm tra cuối chủ điểm. Nguồn: Ngữ pháp Tiếng Anh – Unit 11; Bài tập Tiếng Anh 6 – Unit 1 & 7.','Tự dùng Present Simple trong câu đơn giản và đạt tối thiểu 80%.',2,'quiz',15,80,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 11; Bài tập Tiếng Anh 6 – Unit 1 & 7","lesson_stage":"apply-test","sections":["Đặt câu","Dịch Việt–Anh","Nói/viết ngắn","Kiểm tra"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

INSERT OR IGNORE INTO units(id,course_id,title,description,order_index,background_color,icon_url,total_lessons,created_at,updated_at)
VALUES('unit-zero-u12','course-en-zero-69','Chủ điểm 12: Present Continuous','Hiện tại tiếp diễn cho hành động đang xảy ra. Nguồn: Ngữ pháp Tiếng Anh – Unit 12; Bài tập Tiếng Anh 6 – Unit 1 & 3.',11,NULL,NULL,3,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u12-01','unit-zero-u12','Hiểu bài: Present Continuous','Giải thích từ nền tảng, dùng ví dụ ngắn và dễ hiểu. Nguồn: Ngữ pháp Tiếng Anh – Unit 12; Bài tập Tiếng Anh 6 – Unit 1 & 3.','Nắm được quy tắc chính của Present Continuous.',0,'lesson',10,75,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 12; Bài tập Tiếng Anh 6 – Unit 1 & 3","lesson_stage":"learn","sections":["Giải thích","Ví dụ","Từ/cụm cần nhớ"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u12-02','unit-zero-u12','Luyện tập: Present Continuous','Luyện nhận biết, điền từ, chọn đáp án và sửa lỗi theo tài liệu nguồn. Nguồn: Ngữ pháp Tiếng Anh – Unit 12; Bài tập Tiếng Anh 6 – Unit 1 & 3.','Làm đúng các dạng bài cơ bản của Present Continuous.',1,'practice',10,80,0,25,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 12; Bài tập Tiếng Anh 6 – Unit 1 & 3","lesson_stage":"practice","sections":["Nhận biết","Điền/chọn đáp án","Sửa lỗi"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u12-03','unit-zero-u12','Ứng dụng & kiểm tra: Present Continuous','Đặt câu, dịch Việt–Anh, nói/viết ngắn và kiểm tra cuối chủ điểm. Nguồn: Ngữ pháp Tiếng Anh – Unit 12; Bài tập Tiếng Anh 6 – Unit 1 & 3.','Tự dùng Present Continuous trong câu đơn giản và đạt tối thiểu 80%.',2,'quiz',15,80,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 12; Bài tập Tiếng Anh 6 – Unit 1 & 3","lesson_stage":"apply-test","sections":["Đặt câu","Dịch Việt–Anh","Nói/viết ngắn","Kiểm tra"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

INSERT OR IGNORE INTO units(id,course_id,title,description,order_index,background_color,icon_url,total_lessons,created_at,updated_at)
VALUES('unit-zero-u13','course-en-zero-69','Chủ điểm 13: Present Simple vs Present Continuous','Phân biệt thói quen và hành động đang diễn ra. Nguồn: Ngữ pháp Tiếng Anh – Unit 13; Bài tập Tiếng Anh 6 – Unit 1.',12,NULL,NULL,3,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u13-01','unit-zero-u13','Hiểu bài: Present Simple vs Present Continuous','Giải thích từ nền tảng, dùng ví dụ ngắn và dễ hiểu. Nguồn: Ngữ pháp Tiếng Anh – Unit 13; Bài tập Tiếng Anh 6 – Unit 1.','Nắm được quy tắc chính của Present Simple vs Present Continuous.',0,'lesson',10,75,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 13; Bài tập Tiếng Anh 6 – Unit 1","lesson_stage":"learn","sections":["Giải thích","Ví dụ","Từ/cụm cần nhớ"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u13-02','unit-zero-u13','Luyện tập: Present Simple vs Present Continuous','Luyện nhận biết, điền từ, chọn đáp án và sửa lỗi theo tài liệu nguồn. Nguồn: Ngữ pháp Tiếng Anh – Unit 13; Bài tập Tiếng Anh 6 – Unit 1.','Làm đúng các dạng bài cơ bản của Present Simple vs Present Continuous.',1,'practice',10,80,0,25,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 13; Bài tập Tiếng Anh 6 – Unit 1","lesson_stage":"practice","sections":["Nhận biết","Điền/chọn đáp án","Sửa lỗi"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u13-03','unit-zero-u13','Ứng dụng & kiểm tra: Present Simple vs Present Continuous','Đặt câu, dịch Việt–Anh, nói/viết ngắn và kiểm tra cuối chủ điểm. Nguồn: Ngữ pháp Tiếng Anh – Unit 13; Bài tập Tiếng Anh 6 – Unit 1.','Tự dùng Present Simple vs Present Continuous trong câu đơn giản và đạt tối thiểu 80%.',2,'quiz',15,80,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 13; Bài tập Tiếng Anh 6 – Unit 1","lesson_stage":"apply-test","sections":["Đặt câu","Dịch Việt–Anh","Nói/viết ngắn","Kiểm tra"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

INSERT OR IGNORE INTO units(id,course_id,title,description,order_index,background_color,icon_url,total_lessons,created_at,updated_at)
VALUES('unit-zero-u14','course-en-zero-69','Chủ điểm 14: Countable and Uncountable Nouns','Danh từ đếm được/không đếm được; a/an, some, any. Nguồn: Ngữ pháp Tiếng Anh – Unit 14.',13,NULL,NULL,3,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u14-01','unit-zero-u14','Hiểu bài: Countable and Uncountable Nouns','Giải thích từ nền tảng, dùng ví dụ ngắn và dễ hiểu. Nguồn: Ngữ pháp Tiếng Anh – Unit 14.','Nắm được quy tắc chính của Countable and Uncountable Nouns.',0,'lesson',10,75,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 14","lesson_stage":"learn","sections":["Giải thích","Ví dụ","Từ/cụm cần nhớ"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u14-02','unit-zero-u14','Luyện tập: Countable and Uncountable Nouns','Luyện nhận biết, điền từ, chọn đáp án và sửa lỗi theo tài liệu nguồn. Nguồn: Ngữ pháp Tiếng Anh – Unit 14.','Làm đúng các dạng bài cơ bản của Countable and Uncountable Nouns.',1,'practice',10,80,0,25,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 14","lesson_stage":"practice","sections":["Nhận biết","Điền/chọn đáp án","Sửa lỗi"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u14-03','unit-zero-u14','Ứng dụng & kiểm tra: Countable and Uncountable Nouns','Đặt câu, dịch Việt–Anh, nói/viết ngắn và kiểm tra cuối chủ điểm. Nguồn: Ngữ pháp Tiếng Anh – Unit 14.','Tự dùng Countable and Uncountable Nouns trong câu đơn giản và đạt tối thiểu 80%.',2,'quiz',15,80,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 14","lesson_stage":"apply-test","sections":["Đặt câu","Dịch Việt–Anh","Nói/viết ngắn","Kiểm tra"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

INSERT OR IGNORE INTO units(id,course_id,title,description,order_index,background_color,icon_url,total_lessons,created_at,updated_at)
VALUES('unit-zero-u15','course-en-zero-69','Chủ điểm 15: Questions','Câu hỏi Yes/No và Wh-: what, when, where, who, why, how… Nguồn: Ngữ pháp Tiếng Anh – Unit 15; bài Speaking trong Bài tập Tiếng Anh 6.',14,NULL,NULL,3,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u15-01','unit-zero-u15','Hiểu bài: Questions','Giải thích từ nền tảng, dùng ví dụ ngắn và dễ hiểu. Nguồn: Ngữ pháp Tiếng Anh – Unit 15; bài Speaking trong Bài tập Tiếng Anh 6.','Nắm được quy tắc chính của Questions.',0,'lesson',10,75,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 15; bài Speaking trong Bài tập Tiếng Anh 6","lesson_stage":"learn","sections":["Giải thích","Ví dụ","Từ/cụm cần nhớ"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u15-02','unit-zero-u15','Luyện tập: Questions','Luyện nhận biết, điền từ, chọn đáp án và sửa lỗi theo tài liệu nguồn. Nguồn: Ngữ pháp Tiếng Anh – Unit 15; bài Speaking trong Bài tập Tiếng Anh 6.','Làm đúng các dạng bài cơ bản của Questions.',1,'practice',10,80,0,25,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 15; bài Speaking trong Bài tập Tiếng Anh 6","lesson_stage":"practice","sections":["Nhận biết","Điền/chọn đáp án","Sửa lỗi"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u15-03','unit-zero-u15','Ứng dụng & kiểm tra: Questions','Đặt câu, dịch Việt–Anh, nói/viết ngắn và kiểm tra cuối chủ điểm. Nguồn: Ngữ pháp Tiếng Anh – Unit 15; bài Speaking trong Bài tập Tiếng Anh 6.','Tự dùng Questions trong câu đơn giản và đạt tối thiểu 80%.',2,'quiz',15,80,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 15; bài Speaking trong Bài tập Tiếng Anh 6","lesson_stage":"apply-test","sections":["Đặt câu","Dịch Việt–Anh","Nói/viết ngắn","Kiểm tra"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

INSERT OR IGNORE INTO units(id,course_id,title,description,order_index,background_color,icon_url,total_lessons,created_at,updated_at)
VALUES('unit-zero-u16','course-en-zero-69','Chủ điểm 16: Pronouns','Đại từ tân ngữ và ôn hệ thống đại từ. Nguồn: Ngữ pháp Tiếng Anh – Unit 16.',15,NULL,NULL,3,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u16-01','unit-zero-u16','Hiểu bài: Pronouns','Giải thích từ nền tảng, dùng ví dụ ngắn và dễ hiểu. Nguồn: Ngữ pháp Tiếng Anh – Unit 16.','Nắm được quy tắc chính của Pronouns.',0,'lesson',10,75,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 16","lesson_stage":"learn","sections":["Giải thích","Ví dụ","Từ/cụm cần nhớ"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u16-02','unit-zero-u16','Luyện tập: Pronouns','Luyện nhận biết, điền từ, chọn đáp án và sửa lỗi theo tài liệu nguồn. Nguồn: Ngữ pháp Tiếng Anh – Unit 16.','Làm đúng các dạng bài cơ bản của Pronouns.',1,'practice',10,80,0,25,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 16","lesson_stage":"practice","sections":["Nhận biết","Điền/chọn đáp án","Sửa lỗi"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u16-03','unit-zero-u16','Ứng dụng & kiểm tra: Pronouns','Đặt câu, dịch Việt–Anh, nói/viết ngắn và kiểm tra cuối chủ điểm. Nguồn: Ngữ pháp Tiếng Anh – Unit 16.','Tự dùng Pronouns trong câu đơn giản và đạt tối thiểu 80%.',2,'quiz',15,80,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 16","lesson_stage":"apply-test","sections":["Đặt câu","Dịch Việt–Anh","Nói/viết ngắn","Kiểm tra"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

INSERT OR IGNORE INTO units(id,course_id,title,description,order_index,background_color,icon_url,total_lessons,created_at,updated_at)
VALUES('unit-zero-u17','course-en-zero-69','Chủ điểm 17: Past Simple','Quá khứ đơn với to be, động từ thường và động từ bất quy tắc. Nguồn: Ngữ pháp Tiếng Anh – Unit 17; Bài tập Tiếng Anh 6 – Unit 8.',16,NULL,NULL,3,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u17-01','unit-zero-u17','Hiểu bài: Past Simple','Giải thích từ nền tảng, dùng ví dụ ngắn và dễ hiểu. Nguồn: Ngữ pháp Tiếng Anh – Unit 17; Bài tập Tiếng Anh 6 – Unit 8.','Nắm được quy tắc chính của Past Simple.',0,'lesson',10,75,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 17; Bài tập Tiếng Anh 6 – Unit 8","lesson_stage":"learn","sections":["Giải thích","Ví dụ","Từ/cụm cần nhớ"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u17-02','unit-zero-u17','Luyện tập: Past Simple','Luyện nhận biết, điền từ, chọn đáp án và sửa lỗi theo tài liệu nguồn. Nguồn: Ngữ pháp Tiếng Anh – Unit 17; Bài tập Tiếng Anh 6 – Unit 8.','Làm đúng các dạng bài cơ bản của Past Simple.',1,'practice',10,80,0,25,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 17; Bài tập Tiếng Anh 6 – Unit 8","lesson_stage":"practice","sections":["Nhận biết","Điền/chọn đáp án","Sửa lỗi"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u17-03','unit-zero-u17','Ứng dụng & kiểm tra: Past Simple','Đặt câu, dịch Việt–Anh, nói/viết ngắn và kiểm tra cuối chủ điểm. Nguồn: Ngữ pháp Tiếng Anh – Unit 17; Bài tập Tiếng Anh 6 – Unit 8.','Tự dùng Past Simple trong câu đơn giản và đạt tối thiểu 80%.',2,'quiz',15,80,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 17; Bài tập Tiếng Anh 6 – Unit 8","lesson_stage":"apply-test","sections":["Đặt câu","Dịch Việt–Anh","Nói/viết ngắn","Kiểm tra"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

INSERT OR IGNORE INTO units(id,course_id,title,description,order_index,background_color,icon_url,total_lessons,created_at,updated_at)
VALUES('unit-zero-u18','course-en-zero-69','Chủ điểm 18: Future: Be Going To / Will','Tương lai với be going to và will; mở rộng will/won’t, might từ bài nguồn. Nguồn: Ngữ pháp Tiếng Anh – Unit 18; Bài tập Tiếng Anh 6 – Unit 6 & 10.',17,NULL,NULL,3,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u18-01','unit-zero-u18','Hiểu bài: Future: Be Going To / Will','Giải thích từ nền tảng, dùng ví dụ ngắn và dễ hiểu. Nguồn: Ngữ pháp Tiếng Anh – Unit 18; Bài tập Tiếng Anh 6 – Unit 6 & 10.','Nắm được quy tắc chính của Future: Be Going To / Will.',0,'lesson',10,75,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 18; Bài tập Tiếng Anh 6 – Unit 6 & 10","lesson_stage":"learn","sections":["Giải thích","Ví dụ","Từ/cụm cần nhớ"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u18-02','unit-zero-u18','Luyện tập: Future: Be Going To / Will','Luyện nhận biết, điền từ, chọn đáp án và sửa lỗi theo tài liệu nguồn. Nguồn: Ngữ pháp Tiếng Anh – Unit 18; Bài tập Tiếng Anh 6 – Unit 6 & 10.','Làm đúng các dạng bài cơ bản của Future: Be Going To / Will.',1,'practice',10,80,0,25,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 18; Bài tập Tiếng Anh 6 – Unit 6 & 10","lesson_stage":"practice","sections":["Nhận biết","Điền/chọn đáp án","Sửa lỗi"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u18-03','unit-zero-u18','Ứng dụng & kiểm tra: Future: Be Going To / Will','Đặt câu, dịch Việt–Anh, nói/viết ngắn và kiểm tra cuối chủ điểm. Nguồn: Ngữ pháp Tiếng Anh – Unit 18; Bài tập Tiếng Anh 6 – Unit 6 & 10.','Tự dùng Future: Be Going To / Will trong câu đơn giản và đạt tối thiểu 80%.',2,'quiz',15,80,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 18; Bài tập Tiếng Anh 6 – Unit 6 & 10","lesson_stage":"apply-test","sections":["Đặt câu","Dịch Việt–Anh","Nói/viết ngắn","Kiểm tra"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

INSERT OR IGNORE INTO units(id,course_id,title,description,order_index,background_color,icon_url,total_lessons,created_at,updated_at)
VALUES('unit-zero-u19','course-en-zero-69','Chủ điểm 19: Adjectives','Tính từ; mô tả người/vật; so sánh hơn và so sánh nhất qua bài nguồn. Nguồn: Ngữ pháp Tiếng Anh – Unit 19; Bài tập Tiếng Anh 6 – Unit 3, 4 & 5.',18,NULL,NULL,3,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u19-01','unit-zero-u19','Hiểu bài: Adjectives','Giải thích từ nền tảng, dùng ví dụ ngắn và dễ hiểu. Nguồn: Ngữ pháp Tiếng Anh – Unit 19; Bài tập Tiếng Anh 6 – Unit 3, 4 & 5.','Nắm được quy tắc chính của Adjectives.',0,'lesson',10,75,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 19; Bài tập Tiếng Anh 6 – Unit 3, 4 & 5","lesson_stage":"learn","sections":["Giải thích","Ví dụ","Từ/cụm cần nhớ"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u19-02','unit-zero-u19','Luyện tập: Adjectives','Luyện nhận biết, điền từ, chọn đáp án và sửa lỗi theo tài liệu nguồn. Nguồn: Ngữ pháp Tiếng Anh – Unit 19; Bài tập Tiếng Anh 6 – Unit 3, 4 & 5.','Làm đúng các dạng bài cơ bản của Adjectives.',1,'practice',10,80,0,25,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 19; Bài tập Tiếng Anh 6 – Unit 3, 4 & 5","lesson_stage":"practice","sections":["Nhận biết","Điền/chọn đáp án","Sửa lỗi"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u19-03','unit-zero-u19','Ứng dụng & kiểm tra: Adjectives','Đặt câu, dịch Việt–Anh, nói/viết ngắn và kiểm tra cuối chủ điểm. Nguồn: Ngữ pháp Tiếng Anh – Unit 19; Bài tập Tiếng Anh 6 – Unit 3, 4 & 5.','Tự dùng Adjectives trong câu đơn giản và đạt tối thiểu 80%.',2,'quiz',15,80,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 19; Bài tập Tiếng Anh 6 – Unit 3, 4 & 5","lesson_stage":"apply-test","sections":["Đặt câu","Dịch Việt–Anh","Nói/viết ngắn","Kiểm tra"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

INSERT OR IGNORE INTO units(id,course_id,title,description,order_index,background_color,icon_url,total_lessons,created_at,updated_at)
VALUES('unit-zero-u20','course-en-zero-69','Chủ điểm 20: Adverbs','Trạng từ chỉ cách thức, tần suất, thời gian, nơi chốn và mức độ. Nguồn: Ngữ pháp Tiếng Anh – Unit 20.',19,NULL,NULL,3,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u20-01','unit-zero-u20','Hiểu bài: Adverbs','Giải thích từ nền tảng, dùng ví dụ ngắn và dễ hiểu. Nguồn: Ngữ pháp Tiếng Anh – Unit 20.','Nắm được quy tắc chính của Adverbs.',0,'lesson',10,75,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 20","lesson_stage":"learn","sections":["Giải thích","Ví dụ","Từ/cụm cần nhớ"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u20-02','unit-zero-u20','Luyện tập: Adverbs','Luyện nhận biết, điền từ, chọn đáp án và sửa lỗi theo tài liệu nguồn. Nguồn: Ngữ pháp Tiếng Anh – Unit 20.','Làm đúng các dạng bài cơ bản của Adverbs.',1,'practice',10,80,0,25,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 20","lesson_stage":"practice","sections":["Nhận biết","Điền/chọn đáp án","Sửa lỗi"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u20-03','unit-zero-u20','Ứng dụng & kiểm tra: Adverbs','Đặt câu, dịch Việt–Anh, nói/viết ngắn và kiểm tra cuối chủ điểm. Nguồn: Ngữ pháp Tiếng Anh – Unit 20.','Tự dùng Adverbs trong câu đơn giản và đạt tối thiểu 80%.',2,'quiz',15,80,0,20,'[]','{"source_basis":"Ngữ pháp Tiếng Anh – Unit 20","lesson_stage":"apply-test","sections":["Đặt câu","Dịch Việt–Anh","Nói/viết ngắn","Kiểm tra"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

INSERT OR IGNORE INTO units(id,course_id,title,description,order_index,background_color,icon_url,total_lessons,created_at,updated_at)
VALUES('unit-zero-u21','course-en-zero-69','Chủ điểm 21: Present Perfect','Hiện tại hoàn thành, ever/never, already/yet, for/since; phân biệt với quá khứ đơn. Nguồn: Bài tập Tiếng Anh 6 – Unit 9.',20,NULL,NULL,3,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u21-01','unit-zero-u21','Hiểu bài: Present Perfect','Giải thích từ nền tảng, dùng ví dụ ngắn và dễ hiểu. Nguồn: Bài tập Tiếng Anh 6 – Unit 9.','Nắm được quy tắc chính của Present Perfect.',0,'lesson',10,75,0,20,'[]','{"source_basis":"Bài tập Tiếng Anh 6 – Unit 9","lesson_stage":"learn","sections":["Giải thích","Ví dụ","Từ/cụm cần nhớ"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u21-02','unit-zero-u21','Luyện tập: Present Perfect','Luyện nhận biết, điền từ, chọn đáp án và sửa lỗi theo tài liệu nguồn. Nguồn: Bài tập Tiếng Anh 6 – Unit 9.','Làm đúng các dạng bài cơ bản của Present Perfect.',1,'practice',10,80,0,25,'[]','{"source_basis":"Bài tập Tiếng Anh 6 – Unit 9","lesson_stage":"practice","sections":["Nhận biết","Điền/chọn đáp án","Sửa lỗi"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u21-03','unit-zero-u21','Ứng dụng & kiểm tra: Present Perfect','Đặt câu, dịch Việt–Anh, nói/viết ngắn và kiểm tra cuối chủ điểm. Nguồn: Bài tập Tiếng Anh 6 – Unit 9.','Tự dùng Present Perfect trong câu đơn giản và đạt tối thiểu 80%.',2,'quiz',15,80,0,20,'[]','{"source_basis":"Bài tập Tiếng Anh 6 – Unit 9","lesson_stage":"apply-test","sections":["Đặt câu","Dịch Việt–Anh","Nói/viết ngắn","Kiểm tra"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

INSERT OR IGNORE INTO units(id,course_id,title,description,order_index,background_color,icon_url,total_lessons,created_at,updated_at)
VALUES('unit-zero-u22','course-en-zero-69','Chủ điểm 22: First Conditional','Câu điều kiện loại 1: If + hiện tại đơn, will + động từ. Nguồn: Bài tập Tiếng Anh 6 – Unit 11.',21,NULL,NULL,3,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u22-01','unit-zero-u22','Hiểu bài: First Conditional','Giải thích từ nền tảng, dùng ví dụ ngắn và dễ hiểu. Nguồn: Bài tập Tiếng Anh 6 – Unit 11.','Nắm được quy tắc chính của First Conditional.',0,'lesson',10,75,0,20,'[]','{"source_basis":"Bài tập Tiếng Anh 6 – Unit 11","lesson_stage":"learn","sections":["Giải thích","Ví dụ","Từ/cụm cần nhớ"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u22-02','unit-zero-u22','Luyện tập: First Conditional','Luyện nhận biết, điền từ, chọn đáp án và sửa lỗi theo tài liệu nguồn. Nguồn: Bài tập Tiếng Anh 6 – Unit 11.','Làm đúng các dạng bài cơ bản của First Conditional.',1,'practice',10,80,0,25,'[]','{"source_basis":"Bài tập Tiếng Anh 6 – Unit 11","lesson_stage":"practice","sections":["Nhận biết","Điền/chọn đáp án","Sửa lỗi"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u22-03','unit-zero-u22','Ứng dụng & kiểm tra: First Conditional','Đặt câu, dịch Việt–Anh, nói/viết ngắn và kiểm tra cuối chủ điểm. Nguồn: Bài tập Tiếng Anh 6 – Unit 11.','Tự dùng First Conditional trong câu đơn giản và đạt tối thiểu 80%.',2,'quiz',15,80,0,20,'[]','{"source_basis":"Bài tập Tiếng Anh 6 – Unit 11","lesson_stage":"apply-test","sections":["Đặt câu","Dịch Việt–Anh","Nói/viết ngắn","Kiểm tra"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

INSERT OR IGNORE INTO units(id,course_id,title,description,order_index,background_color,icon_url,total_lessons,created_at,updated_at)
VALUES('unit-zero-u23','course-en-zero-69','Chủ điểm 23: Could / Will Be Able To','Khả năng trong quá khứ, hiện tại và tương lai: could, can, will be able to. Nguồn: Bài tập Tiếng Anh 6 – Unit 12.',22,NULL,NULL,3,'2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u23-01','unit-zero-u23','Hiểu bài: Could / Will Be Able To','Giải thích từ nền tảng, dùng ví dụ ngắn và dễ hiểu. Nguồn: Bài tập Tiếng Anh 6 – Unit 12.','Nắm được quy tắc chính của Could / Will Be Able To.',0,'lesson',10,75,0,20,'[]','{"source_basis":"Bài tập Tiếng Anh 6 – Unit 12","lesson_stage":"learn","sections":["Giải thích","Ví dụ","Từ/cụm cần nhớ"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u23-02','unit-zero-u23','Luyện tập: Could / Will Be Able To','Luyện nhận biết, điền từ, chọn đáp án và sửa lỗi theo tài liệu nguồn. Nguồn: Bài tập Tiếng Anh 6 – Unit 12.','Làm đúng các dạng bài cơ bản của Could / Will Be Able To.',1,'practice',10,80,0,25,'[]','{"source_basis":"Bài tập Tiếng Anh 6 – Unit 12","lesson_stage":"practice","sections":["Nhận biết","Điền/chọn đáp án","Sửa lỗi"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');
INSERT OR IGNORE INTO lessons(id,unit_id,title,description,outcome,order_index,lesson_type,xp_reward,pass_threshold,total_exercises,estimated_minutes,prerequisites,content,created_at,updated_at)
VALUES('lesson-zero-u23-03','unit-zero-u23','Ứng dụng & kiểm tra: Could / Will Be Able To','Đặt câu, dịch Việt–Anh, nói/viết ngắn và kiểm tra cuối chủ điểm. Nguồn: Bài tập Tiếng Anh 6 – Unit 12.','Tự dùng Could / Will Be Able To trong câu đơn giản và đạt tối thiểu 80%.',2,'quiz',15,80,0,20,'[]','{"source_basis":"Bài tập Tiếng Anh 6 – Unit 12","lesson_stage":"apply-test","sections":["Đặt câu","Dịch Việt–Anh","Nói/viết ngắn","Kiểm tra"],"exercises":[]}','2026-10-01T00:00:00.000Z','2026-10-01T00:00:00.000Z');

